spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jlj123
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
  redis:
    host: 192.168.80.129
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml